---
- name: Retrieve latest crictl release
  delegate_to: localhost
  run_once: true
  become: no
  changed_when: False
  shell:
    cmd: curl -s "{{ crictl_releases_url }}"  | grep "browser_download_url\":" | grep "crictl.*\-arm64" | cut -d"\"" -f4
  args:
      warn: no
  register: crictl_release

- name: Set crictl URL and package name
  set_fact:
    crictl_url: "{{ crictl_release.stdout }}"
    crictl_package: "{{ crictl_release.stdout | basename }}"

- name: Download crictl package arm64
  get_url:
    url: "{{ crictl_url }}"
    dest: "/tmp/{{ crictl_package }}"
    owner: root
    group: root
    mode: 0755

- name: Delete crictl if already present
  file:
    path: /usr/local/bin/crictl
    state: absent

- name: Install crictl package
  unarchive:
    src: "/tmp/{{ crictl_package }}"
    dest: /usr/local/bin
    remote_src: yes

- name: Remove temporary files
  file:
    path: "/tmp/{{ crictl_package }}"
    state: absent

- name: Retrieve latest kubectl release
  delegate_to: localhost
  run_once: true
  become: no
  changed_when: False
  uri:
    url: "{{ kubectl_releases_url }}"
    return_content: yes
  register: kubectl_release

- name: Set kubectl URL and package name
  set_fact:
    kubectl_url: "{{ kubectl_download_base_url }}/{{ kubectl_release.content | regex_replace('\n', '') }}/bin/linux/arm64/kubectl"

- name: Delete kubectl if already present
  file:
    path: /usr/local/bin/kubectl
    state: absent

- name: Download kubectl package arm64
  get_url:
    url: "{{ kubectl_url }}"
    dest: "/usr/local/bin/kubectl"
    owner: root
    group: root
    mode: 0755