---
- name: Add br_netfilter to /etc/modules-load.d/
  copy:
      content: "br_netfilter"
      dest: /etc/modules-load.d/br_netfilter.conf
      mode: "u=rw,g=,o="

- name: Load br_netfilter
  modprobe:
      name: br_netfilter
      state: present

- name: Set bridge-nf-call-iptables
  sysctl:
      name: "{{ item }}"
      value: "1"
      state: present
      reload: yes
  loop:
      - net.bridge.bridge-nf-call-iptables
      - net.bridge.bridge-nf-call-ip6tables

