---
- name: Add br_netfilter to /etc/modules-load.d/
  copy:
      content: "br_netfilter"
      dest: /etc/modules-load.d/br_netfilter.conf
      mode: "u=rw,g=,o="

- name: Load br_netfilter
  modprobe:
      name: br_netfilter
      state: present

- name: Set bridge-nf-call-iptables
  sysctl:
      name: "{{ item }}"
      value: "1"
      state: present
      reload: yes
  loop:
      - net.bridge.bridge-nf-call-iptables
      - net.bridge.bridge-nf-call-ip6tables

- name: Activating cgroup support
  lineinfile:
    path: /boot/boot.txt
    regexp: '^setenv"'
    line: 'setenv bootargs console=ttyS1,115200 console=tty0 root=PARTUUID=${uuid} rw rootwait smsc95xx.macaddr="${usbethaddr}" cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  register: cgroup_activation

- name: Compile cgroup changes
  shell:
    cmd: ./mkscr
    chdir: /boot
  become: yes

- name: Rebooting
  reboot:
  when: cgroup_activation is changed
