---
- name: Uninstall k3s and stop services on master
  command: /usr/local/bin/k3s-uninstall.sh
  args:
    removes: /usr/local/bin/k3s
  when: "inventory_hostname == groups['k3s_rpi_master'][0]"

- name: Uninstall k3s and stop services on workers
  command: /usr/local/bin/k3s-agent-uninstall.sh
  args:
    removes: /usr/local/bin/k3s
  when: "inventory_hostname != groups['k3s_rpi_master'][0]"

- name: Remove binaries and data
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/crictl
    - /usr/local/bin/kubectl
    - /etc/crictl.yaml
    - ~{{ dev_user }}/.kube