---
- hosts: k3s_rpi_master
  become: yes
  roles:
    - role: k3s/master

- hosts: k3s_rpi_workers
  become: yes
  roles:
    - role: k3s/node

- name: Post install config
  hosts: k3s_rpi_master
  become: yes
  roles:
    - role: k3s/post-config

- name: Install more nice things
  hosts: localhost
  roles:
    - role: k3s/monitoring
