---
- name: Network configurations
  hosts: k3s_rpi
  become: yes
  tasks:

    - name: Configure local hostname
      template:
        src: "hosts.j2"
        dest: "/etc/hosts"
        owner: "root"
        group: "root"
        mode: 0644

    - name: Configure nss-mdns
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^hosts: (.+)(?<! mdns_minimal \[NOTFOUND=return\]) resolve (.*)$'
        line: 'hosts:\1 mdns_minimal [NOTFOUND=return] resolve \2'
        backrefs: yes

    - name: Enable & start avahi-daemon service
      systemd:
        name: avahi-daemon
        enabled: yes
        state: started

    - name: Enable & start systemd-resolved service
      systemd:
        name: systemd-resolved
        enabled: yes
        state: started

    - name: Restart network
      systemd:
        name: systemd-networkd
        state: restarted
        no_block: yes
