---
- hosts: k3s_rpi
  become: yes
  tasks:

    - name: Initialize pacman keyring
      command: pacman-key --init
      changed_when: False

    - name: Initial setup of master keys
      command: pacman-key --populate archlinuxarm
      changed_when: False

    - name: Update and upgrade pacman packages
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install common packages
      pacman:
        name:
          - base-devel
          - avahi
          - nss-mdns
        state: present

    - name: Set timezone to {{ timezone }}
      timezone:
        name: "{{ timezone }}"

    - name: Check NTP time synchronization
      shell:
        cmd: "timedatectl status | grep -i 'NTP service: inactive'"
      register: ntp_disabled
      changed_when: "'inactive' in ntp_disabled.stdout"
      failed_when: ntp_disabled.rc >=2
      ignore_errors: yes

    - name: Enable NTP time synchronization
      command: timedatectl set-ntp true
      when: ntp_disabled|bool

    - name: Create AUR builder user
      user:
        name: aur_builder
        group: wheel

    - name: Add sudoers permissions to AUR builder
      lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'