---
- hosts: k3s_rpi
  roles:
    - kewlfft.aur # AUR manager installed through ansible-galaxy
  become: yes
  tasks:

    - name: Update pacman cache
      pacman:
        update_cache: yes

    - name: Install utility packages
      pacman:
        name:
          - man
          - man-db
          - net-tools
          - bc
          - zsh
          - vim
          - neovim
          - tmux
          - fzf
          - lsd
          - bat
          - fd
          - git
          - tldr
          - curl
          - wget
          - htop
          - the_silver_searcher
          - cowsay
          - fortune-mod
          - figlet
          - lolcat
          - zip
          - unzip
          - python3
          - python-pip
          - python-pylint
          - i2c-tools
        state: present

    - name: Install AUR command
      shell:
        cmd: bash <(curl -s https://archibold.io/install/aur)
        creates: /usr/bin/aur
      args:
        executable: /usr/bin/bash

    - name: Install yay from AUR
      aur: name=yay use=makepkg state=present
      become: yes
      become_user: aur_builder

    - name: Install extra packages using yay
      aur:
        use: yay
        name:
          - boxes
          - toilet
          - toilet-fonts
          - python-pigpio-git
          - raspi-config
      become: yes
      become_user: aur_builder

    - name: Install Python modules
      pip:
        name: pexpect,RPi.GPIO,spidev,i2clcd,blinkt