---
- name: Setup packages
  hosts: k3s_rpi

  tasks:
    - name: Install extra packages from aur
      kewlfft.aur.aur:
        name:
          - yay
          - oh-my-zsh-git
          - raspi-config-git
          - kubectl-bin
      become: yes
      become_user: aur_builder
