---
- hosts: k3s_rpi
  become: yes
  tasks:

    - name: Create development group {{ dev_group }}
      group:
        name: "{{ dev_group }}"
        state: present

    - name: Create gpio group
      group:
        name: gpio
        state: present

    - name: Create i2c group
      group:
        name: i2c
        state: present

    - name: Check if i2c is enabled
      command: "raspi-config nonint get_i2c"
      register: i2c_disabled
      changed_when: i2c_disabled.stdout == "1"

    - name: Enable i2c
      command: "raspi-config nonint do_i2c 0"
      when: i2c_disabled.stdout == "1"

    - name: Add development user {{ dev_user }}
      user:
        name: "{{ dev_user }}"
        password: "{{ dev_password }}"
        comment: "{{ dev_name }}"
        groups: "{{ def_group }},{{ dev_group }},gpio,i2c,docker"

    - name: Change root password
      user:
        name: root
        password: "{{ root_password }}"

    - name: Create root bashrc
      copy:
        dest: ~/.bashrc
        content: |
          #!/bin/env/ bash
          if [ -f ~/.bash_profile ]; then
              source ~/.bash_profile
          fi

    - name: Set root bash_profile
      copy:
        dest: ~/.bash_profile
        content: |
          # Custom fancy prompt
          export PS1=$'\[\e[36m\][\[\e[31m\]\u@\h:\[\e[33m\]\w\[\e[36m\]]$\[\e[39m\] '

    - name: Set authorized key for development user from current user
      authorized_key:
        user: "{{ dev_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Create development directory
      file:
        path: "{{ dev_directory }}"
        state: directory
        owner: "{{ dev_user }}"
        group: "{{ dev_group }}"
        mode: '0755'

    - name: Retrieving dotfiles base directory
      set_fact:
        dotfiles_repo_target: "{{ dot_files_repo_url | basename | regex_replace('^(.+).git$','\\1') }}"

    - name: Retrieving dotfiles target directory
      set_fact:
        dotfiles_dir: "{{ dev_directory }}/{{ dotfiles_repo_target }}"

    - name: Clone dotfiles
      git:
        repo: '{{ dot_files_repo_url }}'
        dest: "{{ dotfiles_dir }}"
        version: "{{ dot_files_repo_version }}"
        force: yes

    - name: Set dotfiles permissions
      file:
        path: "{{ dotfiles_dir }}"
        group: "{{ dev_group }}"
        mode: '0775'
        recurse: yes

    - name: Create vi symbolic link
      file:
        src: /usr/bin/vim
        dest: /usr/bin/vi
        owner: root
        group: root
        state: link