---
- name: Create users
  hosts: k3s_rpi
  become: yes
  tasks:

    - name: Create development group {{ dev_group }}
      group:
        name: "{{ dev_group }}"
        state: present

    - name: Create gpio group
      group:
        name: gpio
        state: present

    - name: Create i2c group
      group:
        name: i2c
        state: present

    - name: Check if i2c is enabled
      command: "raspi-config nonint get_i2c"
      register: i2c_disabled
      changed_when: i2c_disabled.stdout == "1"

    - name: Enable i2c
      command: "raspi-config nonint do_i2c 0"
      when: i2c_disabled.stdout == "1"

    - name: Fix alarm user
      user:
        name: "{{ rpi_username }}"
        password: "{{ dev_password }}"
        comment: "{{ dev_name }}"
        groups: "{{ def_group }},{{ dev_group }},gpio,i2c,docker,network"
        shell: /bin/zsh

    - name: Copy oh-my-zsh config
      copy:
        src: "/usr/share/oh-my-zsh/zshrc"
        dest: "/home/{{ rpi_username }}/.zshrc"
        owner: "{{ rpi_username }}"
        group: "{{ rpi_username }}"
        remote_src: yes

    - name: Celete alarm shell
      user:
        name: alarm
        shell: /bin/zsh

    - name: Change root password
      user:
        name: root
        password: "{{ root_password }}"
        shell: /bin/zsh


    - name: Set authorized key for development user from current user
      authorized_key:
        user: "{{ rpi_username }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Create development directory
      file:
        path: "{{ dev_directory }}"
        state: directory
        owner: "{{ rpi_username }}"
        group: "{{ dev_group }}"
        mode: '0755'
