---
- name: yay -Syu
  hosts: k3s_rpi
  become: yes
  become_user: aur_builder
  tasks:
  - name: Update packages
    register: result
    changed_when: result.packages is defined and (result.packages | length > 0)
    community.general.pacman:
      executable: "yay"
      upgrade: yes
      update_cache: yes
