---
# Globals
#########

ansible_python_interpreter: auto_silent

k3s_releases_url: "https://api.github.com/repos/rancher/k3s/releases/latest"

# Users and groups
##################

# Default raspberry pi login
rpi_username: alarm
rpi_password: alarm

# Ansible sudo password
ansible_sudo_pass: "{{ rpi_username }}"

# Defines the ansible user to use when connecting to devices
ansible_user: "{{ rpi_username }}"

dev_name: Assaf Sapir
dev_group: dev
def_group: wheel
dev_directory: /Projects
dev_password: $6$pMV0q3nKr8RwnL/d$sBHiDdO7SqsaBQZi.YFKgmX62kFx5XIegbHD2xTdfQL0SQU2H8NuRAXEjUkoh8cZwoFKcr5MB1UUvBzI8wkub/

root_password: $6$pMV0q3nKr8RwnL/d$sBHiDdO7SqsaBQZi.YFKgmX62kFx5XIegbHD2xTdfQL0SQU2H8NuRAXEjUkoh8cZwoFKcr5MB1UUvBzI8wkub/

# System config
###############

# Default timezone
timezone: "Asia/Jerusalem"
locale: "en_US.UTF-8"

systemd_dir: /etc/systemd/system

# K3S
#####

master_name: "{{ groups['k3s_rpi_master'][0] }}"
master_ip: "{{ hostvars[master_name].ansible_host }}"
extra_server_args: "--tls-san k3s.ass.af --bind-address {{ master_ip }} --write-kubeconfig-mode 600 --cluster-init"
extra_agent_args: ""
